### ISSUE TITLE
Composer does not exist and could not be installed.

### ISSUE THREAD

**Issue by ConnorParrish** [xyu/heroku-wp#102]
`./init-composer.sh: line 33: php: command not found
ERROR: Invalid installer signature
Composer does not exist and could not be installed.`

This happens when I run `$ cd heroku-wp && bin/init.sh myappname`

**Comment by ryanburnette** [comment]
What happens when you manually install Composer?

```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```

https://getcomposer.org/download/

**Comment by xyu** [comment]
You will need to have php installed in your local dev environment for any of this to work.
