### ISSUE TITLE
init.sh will fail if push is going to be first ssh connection to Heroku

### ISSUE THREAD

**Issue by ryanburnette** [xyu/heroku-wp#103]
If the `init.sh` script runs and it happens to be the first time the machine is connecting to Heroku via SSH, there's an interactive prompt about adding the new host. This will cause the `init.sh` script to fail until the user interactively makes that first connection to clear it.

If there's a way the bash script could check for this and error out it might save some confusion for anyone in this situation.

**Comment by xyu** [comment]
@jjb in #94 mentioned that Heroku's default protocol for git is http perhaps we should just switch to to that instead of SSH which would solve this edge case and seems like would be more widely supported as HTTPS is the default transport. What do you think?

**Comment by ryanburnette** [comment]
I'm not sure if using HTTPS would actually alleviate this issue. Not that it requires addressing when it is very edge. But would using HTTPS require users to enter login credentials when deploying?

If I get a chance I'll research answers to my own questions there.

This is definitely an edge case that seems a pretty low priority.

**Comment by toniab** [comment]
same issue here

**Comment by xyu** [comment]
This has been fixed by #155
