### ISSUE TITLE
Heroku warns that composer.lock is not up to date with json

### ISSUE THREAD

**Issue by ryanburnette** [xyu/heroku-wp#104]
Every time I deploy I get the warning that the `composer.lock` is not up to date with `composer.json`. I have made sure to run `composer update` and no changes are made to `composer.lock`. It doesn't appear to cause any problems. Anyone else having this happen?

```
remote:        WARNING: Your 'composer.lock' is not up to date with the latest
remote:        changes in 'composer.json'. To ensure you are not getting stale
remote:        dependencies, run 'composer update' on your machine and commit
remote:        any changes to Git before pushing again.
```

**Comment by Tailzip** [comment]
I'm also having this warning message, but everything works fine! 😅

**Comment by xyu** [comment]
@ryanburnette that is quite odd... that seems to indicate that on deploy you're not getting the latest plugins as referenced in your `composer.json` file. Can you try this in the root dir and provide the output?

```
$ bin/composer update --ignore-platform-reqs
```

If you feel comfortable can you also provide the `composer.json` file so I can try and reproduce?

**Comment by ryanburnette** [comment]
I ran `bin/composer update --ignore-platform-reqs` but still got the message when deploying to Heroku.

Here's my `composer.json`.

    // composer.json
    {
      "name": "yet-another-wordpress-project",
      "require": {
        "ext-gd": "*",
        "php": "7.0.*",
        "WordPress/WordPress": "*",
        "automattic/batcache": "dev-master",
        "wpackagist-plugin/redis-cache": "~1",
        "wpackagist-plugin/secure-db-connection": "~1",
        "humanmade/s3-uploads": "~1",
        "wpackagist-plugin/authy-two-factor-authentication": "~3",
        "wpackagist-plugin/jetpack": "~4",
        "wpackagist-plugin/sendgrid-email-delivery-simplified": "~1",
        "wpackagist-plugin/term-management-tools": "~1",
        "wpackagist-plugin/wp-pagenavi": "~2",
        "advanced-custom-fields/advanced-custom-fields-pro": "~5",
    		"delicious-brains/wp-migrate-db-pro": "~1",
        "predis/predis": "~1.0",
        "wp-cli/wp-cli": "^1.0",
        "wpackagist-plugin/wordpress-seo": "^4.4",
        "wpackagist-plugin/disable-comments": "^2.6",
        "airmanbzh/php-html-generator": "~1"
      },
      "suggest": {
        "wpackagist-plugin/cloudflare-cache-purge": "Purges cached pages on CF.",
        "trepmal/wp-revisions-cli": "WP CLI tool for cleaning up revisions (dev-master)"
      },
      "repositories": [
        {
          "type": "package",
          "package": {
            "name": "WordPress/WordPress",
            "version": "4.7.3",
            "dist": {
              "type": "zip",
              "url": "https://github.com/WordPress/WordPress/archive/4.7.3.zip"
            }
          }
        },
        {
          "type": "vcs",
          "url": "https://github.com/xyu/batcache"
        },
        {
          "type": "composer",
          "url": "https://wpackagist.org"
        },
        {
          "type": "composer",
          "url": "https://wp-cli.org/package-index"
        },
        {
          "type": "package",
          "package": {
            "name": "advanced-custom-fields/advanced-custom-fields-pro",
            "version": "5.5.11",
            "type": "wordpress-plugin",
            "dist": {
              "type": "zip",
              "url": "https://connect.advancedcustomfields.com/index.php?t=5.5.11&p=pro&a=download&k={key}"
            }
          }
        },
        {
          "type": "package",
          "package": {
            "name": "delicious-brains/wp-migrate-db-pro",
            "version": "1.7.1",
            "type": "wordpress-plugin",
            "dist": {
              "type": "zip",
              "url": "https://ryanburnette.s3-us-west-2.amazonaws.com/wp-migrate-db-pro-1.7.1.zip"  
            }
          }
        }
      ],
      "extra": {
        "installer-paths": {
          "vendor/WordPress/WordPress/wp-content/mu-plugins/{$name}/": [
            "automattic/batcache",
            "wpackagist-plugin/redis-cache",
            "wpackagist-plugin/secure-db-connection"
          ],
          "vendor/WordPress/WordPress/wp-content/plugins/{$name}/": [ "type:wordpress-plugin" ],
          "vendor/WordPress/WordPress/wp-content/themes/{$name}/": [ "type:wordpress-theme" ]
        }
      },
      "scripts": {
        "post-install-cmd": [
          "./support/app_slug_compile.sh"
        ]
      }
    }

**Comment by gururajjeerge** [comment]
**This is the exact error we can see in terminal.**

[Composer\Downloader\TransportException]                                                                                                  The "http://packagist.org/p/providerlatest%24871b089655ba04c296abe27ecee6fe6830a25c1203a7a40e3d604c224d8b87cb.json" file could not be downloaded (HTTP/1.1 302 Found)

**Comment by arapmelly** [comment]
did you ever solve this?

**Comment by hamidb14** [comment]
I had this the same problem for 2 days.

this is my experience about this problem:

> you must read documentation before do anything.

I forgot add `composer.lock` to git.

that is remembered in heroku documentation:
> don't forget add both files to git! 

so it's better that we read documentation carefully and without any fear.

**Comment by atesztoth** [comment]
In my case composer.lock is added, on localhost, no errors, but while deploying. Ah man...

**Comment by ryanburnette** [comment]
I continue to have this error. I have always had `composer.json` and `composer.lock` at the same state in git.

**Comment by xyu** [comment]
Both files have to be added and committed in your deployment branch.

**Comment by ryanburnette** [comment]
@hamidb80 @xyu  I have always had the most up-to-date `composer.lock` in my version control. The issue persists for me any others.

**Comment by ryanburnette** [comment]
@hamidb80 Thanks for telling me to read the documentation. That was very helpful. 😤👎

**Comment by ryanburnette** [comment]
The issue was caused by using a different version of PHP in development than production. Version 7.2.something was writing the lock then 7.3.11 was running on Heroku.

**Comment by Blindpupil** [comment]
Removing a buildpack I had recently added fixed the issue for me
