### ISSUE TITLE
Vagrant's nginx.conf would benefit from sendfile off

### ISSUE THREAD

**Issue by ryanburnette** [xyu/heroku-wp#105]
If you're developing locally in Vagrant using Nginx, you'll want to set `sendfile off;` in `nginx.conf`. If @xyu can give me a suggestion on how to script that into the Vagrant provisioning I'll be glad to do a pull request.

Without `sendfile off;` Nginx doesn't seem to consistently read the source file in the root directory making development problematic when frequent changes are made.

**Comment by xyu** [comment]
Thanks for the PR closing this issue.
