### ISSUE TITLE
Cannot modify header information

### ISSUE THREAD

**Issue by ryanburnette** [xyu/heroku-wp#111]
I'm getting this error intermittently after importing a MySQL database.

Restarting dynos and running `heroku run wp cache flush` doesn't help. It does seem that waiting for a while clears it up.

```
Warning: mysqli_set_charset(): Error executing query in /app/public.built/wp-includes/wp-db.php on line 823

Warning: Cannot modify header information - headers already sent by (output started at /app/public.built/wp-includes/wp-db.php:823) in /app/public.built/wp-includes/pluggable.php on line 1179
```

**Comment by xyu** [comment]
This is odd, do you happen to have any other error logs from Heroku when this happens? The only thing that happens in the core file where the error occurs is a `mysqli_set_charset()` call so seems like either the connection was not established correctly or MySQL was not able to switch the charset.

What charset do you have your tables currently set to? Perhaps you need 
`utf8mb4`/`utf8mb4_general_ci` for `DB_CHARSET` and `DB_COLLATE` instead?

Here's are what valid values are for MariaDB (if using Jaws MariaDB):
https://mariadb.com/kb/en/mariadb/supported-character-sets-and-collations/

And more info about converting charsets:
https://codex.wordpress.org/Converting_Database_Character_Sets

**Comment by ryanburnette** [comment]
I updated the original comment. This error started after importing a database from MySQL. Setting `DB_CHARSET` and `DB_COLLATE` fixed the issue for me. I no longer have any details about the environment I was using when I had the issue.

**Comment by lacabra** [comment]
I experienced this same error when using Heroku's ClearDB addon, and then hitting the `max_questions` limit of the Free plan. The error only become apparent when trying to access the DB from the command line right after the site had crashed, and getting this additional error message:
`User '____' has exceeded the 'max_questions' resource (current value: 3600) (1226)`
Which then led me to this FAQ: http://w2.cleardb.net/faqs/#multi_7
