### ISSUE TITLE
Run locally Nginx + heroku-wp

### ISSUE THREAD

**Issue by laranicolas** [xyu/heroku-wp#112]
Hey how are you?

I already install nginx, php-fpm, mysql and all staff to execute php files and is working (tested).

The problem ocurred because I want to install a theme with plugins on heroku, but it is impossible because it doesn't have permissions to write on dynos on heroku. I thought to run locally, install theme + plugins and then push to heroku.

I redirect to `vendor/WordPress/WordPress/index.php` directory and I see next screen:

<img width="1440" alt="screen shot 2017-03-28 at 5 05 51 pm" src="https://cloud.githubusercontent.com/assets/1824473/24424994/dbbf1b06-13d8-11e7-9421-7fd84d3d6965.png">

but I need to relate with `wp-config.php` that is on `public` directory, how can I solve this?

or there is another solution to push custom plugins from a custom theme?

**Comment by xyu** [comment]
@laranicolas You will need to create a `plugins` and `themes` folder within the `wp-content` dir here:

https://github.com/xyu/heroku-wp/tree/nginx-php7/public/wp-content

Then commit your theme and plugin files into git. As an alternative, the preferred method if your theme and plugins are standard non customized and published to the WordPress.org repos is to simply add them to the require section of composer then update the lock file:

https://github.com/xyu/heroku-wp/blob/nginx-php7/composer.json#L14-L31
