### ISSUE TITLE
How to include plugins not via composer

### ISSUE THREAD

**Issue by dgursh** [xyu/heroku-wp#115]
Hi, my theme requires a few plugins not available on composer. I have the zip file. Where should I put the files for the plugin and how do I call it on the build when I push to heroku? Thanks.

**Comment by ryanburnette** [comment]
I know you closed your issue, but...

You can commit plugins to the repository.

You can also look into [wpackagist](https://wpackagist.org/) which mirrors the WordPress plugin and theme directories as a Composer repository.

Some plugins aren't available via Composer, but you can have Composer download them for you which is preferable to committing code that isn't yours to your repository and causing a mess. You can [look at this commit](https://github.com/xyu/heroku-wp/pull/107/commits/2e9451161a808f3c5d1f24a6947482b9394a0b02) to see how I am loading a plugin that isn't on wpackagist with Composer. This approach should work for other plugins with a few tweaks.

**Comment by dgursh** [comment]
Thanks @ryanburnette.
