### ISSUE TITLE
Heroku SSL

### ISSUE THREAD

**Issue by dgursh** [xyu/heroku-wp#116]
Quick question about the server. So, this is using NGINX not Apache? Right now, when I upgrade to Hobby dev I get a free SSL and the certificate seems to be working on everything besides the home page. Do you have any idea why?

**Comment by ryanburnette** [comment]
Correct, it's using Nginx, not Apache.

Maybe the pages that aren't showing secure are loading non-HTTPS assets.

**Comment by dgursh** [comment]
What does that mean exactly? Right now it loads with https on the home page for a millisecond and then turns back to http. Chrome is saying that it is trying to load unsafe scripts?

https://support.google.com/chrome/answer/1342714?p=unauthenticated&visit_id=1-636280467186264826-526677993&rd=1

Any Ideas how I can fix this. Again, when I log into the admin panel everything is HTTPS, it's only on the home page for some reason...

**Comment by dgursh** [comment]
@ryanburnette omg you're right. I opened up dev tools and see thousands of errors for pulling assets not over https and refusing the connection. LOL! I just turned off SSL. No need for a single page anyway. Thanks.

**Comment by dgursh** [comment]
@ryanburnette do you know how to change the NGINX settings to http?

**Comment by dgursh** [comment]
For anyone curious it had to do with http calls to assets. Once I removed those, everything worked fine over https.
