### ISSUE TITLE
custom app name redirects failing

### ISSUE THREAD

**Issue by dgursh** [xyu/heroku-wp#117]
Any advice on this issue?

Whenever I visit my custom app name in the browser URL it is automatically redirected to my heroku name

i.e. 

example.com --> www.example.herokuapp.com

My DNS settings are correct. How do I fix this at the app level with NGINX?

**Comment by ryanburnette** [comment]
What do you have in your [General Settings](https://codex.wordpress.org/Settings_General_Screen)?

**Comment by dgursh** [comment]
@ryanburnette you were right, the general settings were the both the old heroku app. So, I changed them to https://example.com and now I'm completely locked out. Can't even access the domain anymore. What do I do? Kind of panicking now...

**Comment by dgursh** [comment]
@ryanburnette kinda desperate here. I downloaded sequel Pro and was able to change the site url and home url back to the originals, but it's still not working. Any ideas? Desperate for help....

**Comment by dgursh** [comment]
@ryanburnette I'll wait for your reply. I re-made my app :(, Hopefully tomorrow you will help me get the right URL, because I have no idea how to configure general settings without breaking the whole thing :(

**Comment by dgursh** [comment]
Had to clear the redis cache. Wow... cannot believe that this is all it was. Any future readers out there. Read the docs and run

```
heroku run wp cache flush
```
