### ISSUE TITLE
SendGrid plugin version 1.11.0 breaking change

### ISSUE THREAD

**Issue by Tailzip** [xyu/heroku-wp#118]
SendGrid plugin version 1.11.0 has been released and has dropped support of username & password authentication method. It only accepts an API key now.

See changelog here: https://github.com/sendgrid/wordpress#changelog

`wp-config.php` file must be updated, and it requires a little bit of extra manual set up to obtain an API key, see here: https://devcenter.heroku.com/articles/sendgrid#create-an-api-key

I'll submit a PR when I have some spare time, hopefully this week.

**Comment by dgursh** [comment]
+1

**Comment by Tailzip** [comment]
PR #121 is ready!

**Comment by xyu** [comment]
#121 merged thanks for the fix!
