### ISSUE TITLE
There is no option to upload the new theme and plugins.

### ISSUE THREAD

**Issue by gururajjeerge** [xyu/heroku-wp#122]
Please provide option to upload themes and install plugins after the installation.

**Comment by punggolzenith** [comment]
try to upload to public/wp-content/themes   or /plugins   , as per your usual wordpress installations.
Or try to write it into composer, neater.

**Comment by abeering** [comment]
Something else which may be good is to figure out which plugins / other configuration is disabling the "Upload Theme" button from the appearance tab after default install / deploy.

**Comment by punggolzenith** [comment]
Perhaps wordpress recognises the inherent "ephemeral" nature of the heroku file system. Even if you can try to upload or install something from the app, it will go missing when your heroku app restarts itself, you can read the heroku documentation for more details.

**Comment by abeering** [comment]
Super relevant point! I agree.

**Comment by xyu** [comment]
@punggolzenith / @abeering yup exactly on point with the ephemeral FS and problems with allowing uploading of things in WP. This is why I've set `DISALLOW_FILE_EDIT` and `DISALLOW_FILE_MODS` explicitly to disable this. :)

https://github.com/xyu/heroku-wp/blob/nginx-php7/public/wp-config.php

**Comment by uttaravadina** [comment]
If not an Upload option then can it be made possible to push a theme to added into `wp-content/themes/` using a `git push`

**Comment by evanjmg** [comment]
@u774r4v4d1n I've done this in public/wp-content/themes and this does not work - the code is committed and theme doesn't appear
