### ISSUE TITLE
Is batcache working?

### ISSUE THREAD

**Issue by ryanburnette** [xyu/heroku-wp#123]
I read through #15, but it's not clear to me right now if I need to add a Memcached addon in Heroku for batcache to work, or if it's working because of Redis somehow.

I have a couple pages on my current project that are database heavy and I really want the output of the pages to be cached to avoid running the heavy query load required to generate the pages.

Is there any way I can do a test to see if batcache is doing its job?

**Comment by ryanburnette** [comment]
I guess I can indirectly say that it probably is. I made 4 requests to the page in fast succession. The first two responses took ~6 seconds, the second two ~.3 seconds.

    # ryanburnette @ ########## in ###################################### on git:master o [11:21:53]
    $ curlt -L https://############.herokuapp.com/#######
    {
     "time_namelookup": 0.000,
     "time_connect": 0.000,
     "time_appconnect": 0.000,
     "time_pretransfer": 0.000,
     "time_redirect": 0.347,
     "time_starttransfer": 0.310,
     "time_total": 6.049
    }

    # ryanburnette @ ########## in ###################################### on git:master o [11:48:37]
    $ curlt -L https://############.herokuapp.com/#######
    {
     "time_namelookup": 0.000,
     "time_connect": 0.000,
     "time_appconnect": 0.000,
     "time_pretransfer": 0.000,
     "time_redirect": 0.362,
     "time_starttransfer": 6.203,
     "time_total": 6.646
    }

    # ryanburnette @ ########## in ###################################### on git:master o [11:48:45]
    $ curlt -L https://############.herokuapp.com/#######
    {
     "time_namelookup": 0.000,
     "time_connect": 0.000,
     "time_appconnect": 0.000,
     "time_pretransfer": 0.000,
     "time_redirect": 0.157,
     "time_starttransfer": 0.055,
     "time_total": 0.291
    }

    # ryanburnette @ ########## in ###################################### on git:master o [11:48:47]
    $ curlt -L https://############.herokuapp.com/#######
    {
     "time_namelookup": 0.000,
     "time_connect": 0.000,
     "time_appconnect": 0.000,
     "time_pretransfer": 0.000,
     "time_redirect": 0.156,
     "time_starttransfer": 0.060,
     "time_total": 0.293
    }

    # ryanburnette @ ########## in ###################################### on git:master o [11:48:50]
    $

**Comment by zcrowe** [comment]
So you did at a memcache module to get this going?

**Comment by ryanburnette** [comment]
The above test is run with only the add-ons provisioned by the init script. I am not running a memcache add-on. I'd still like to know if that's required to gain the benefit of batcache.

**Comment by zcrowe** [comment]
Getting a bit worries this repo has been dumped (which is a massive shame!) - hopefully we'll get a reply :)

**Comment by xyu** [comment]
Howdy @ryanburnette and @zcrowe, I'm so sorry for being unresponsive as I haven't had time to really work on this repo for the past year or so! But to answer your question yes bat cache works out of the box because the `init.sh` adds the free [Heroku Redis add-on](https://elements.heroku.com/addons/heroku-redis) which basically gets you 25 MB of caching. The included Redis Object Cache WP Plugin is also preconfigured to use that cache and Batcache does indeed then piggyback on Redis Object Cache to provide page caching.
