### ISSUE TITLE
Reset to factory settings

### ISSUE THREAD

**Issue by stanleycyang** [xyu/heroku-wp#126]
I made a change to the wordpress URL in settings and now my site is busted. Is there a quick way to reset the wordpress blog to factory settings?

Thanks!

**Comment by ryanburnette** [comment]
[This][1] might address the "busted" state.

[1]: https://github.com/xyu/heroku-wp#q-help-nothing-is-showing-up--ive-polluted-my-cache

**Comment by stanleycyang** [comment]
@ryanburnette just ran it and it did not work. I see that there is a mysql instance tied to it, anyway I can access that?

**Comment by punggolzenith** [comment]
Try changing the settings in wp-config and push to heroku. 

If u really need to u can do some database tools I think I used heidisql. Then u go heroku jawsdb to get all the login details.just rmb to flush cache after changes. And always backup!!
