### ISSUE TITLE
composer could not be installed 

### ISSUE THREAD

**Issue by casufi** [xyu/heroku-wp#132]
I am trying to deploy new app using bash on Windows and getting the following error

`
casufi@DESKTOP-CP0IG6M:/mnt/c/Users/casufi/Projects/heroku-wp$ ./bin/init.sh rogearson-wp
Downloading Composer Installer...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  298k  100  298k    0     0   202k      0  0:00:01  0:00:01 --:--:--  202k
./init-composer.sh: рядок 33: php: команду не знайдено
ERROR: Invalid installer signature
Composer does not exist and could not be installed.
`

**Comment by punggolzenith** [comment]
perhaps you can try installing composer on your windows first by googling...

i don't think the init-composer.sh is meant to run on windows... or perhaps like most of us, use linux?

**Comment by xyu** [comment]
If Composer is not found on the local system then `./init-composer.sh` will try and download the latest Composer directly. Sounds like the download is corrupted here so I guess either run `./init-composer.sh` again or just install Composer manually.

http://getcomposer.org/
