### ISSUE TITLE
Layer slider plugin not supporting

### ISSUE THREAD

**Issue by senthilkumar04** [xyu/heroku-wp#133]
I am trying to use the layer slider plugin to put layer slider on the home page for the website. But the problem is the slider is getting created. But the slides in it, are not saving. Please help....

**Comment by punggolzenith** [comment]
erm, im not sure if this is the right platform to ask these questions...

perhaps you should ask the plugin developer if they support an "ephemeral file" system first...

**Comment by xyu** [comment]
Yeah sorry I can't offer any support for that; if that plugin tries to write to the local disk even when the WP config vars `DISALLOW_FILE_EDIT` and `DISALLOW_FILE_MODS` are set then it will break because Heroku slugs are run on ephemeral instances.
