### ISSUE TITLE
Heroku composer.json & composer.lock errors

### ISSUE THREAD

**Issue by albabosh** [xyu/heroku-wp#138]
-----> Deleting 6 files matching .slugignore patterns.
-----> PHP app detected
 !     WARNING: Your 'composer.json' contains a non-'stable' setting
       for 'minimum-stability'. This may cause the installation of
       unstable versions of runtimes and extensions during this deploy.
       It is recommended that you always use stability flags instead,
       even if you have 'prefer-stable' enabled. For more information,
       see https://getcomposer.org/doc/01-basic-usage.md#stability
-----> Bootstrapping...
-----> Installing platform packages...
 !     ERROR: Couldn't load 'composer.lock'; it must be a valid lock
       file generated by Composer and be in a consistent state.
       Check above for any parse errors and address them if necessary.
       Run 'composer update', add/commit the change, then push again.
 !     Push rejected, failed to compile PHP app.
 !     Push failed

**Comment by punggolzenith** [comment]
I think to give some help, we need to know at least what is inside ur composer.json file.

Also what command did u run to lock the composer file?
