### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by albabosh** [xyu/heroku-wp#139]
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Deploy failed for ...

What is wrong here ? (I have done 'heroku login' before, credentials are correct

**Comment by cenobitedk** [comment]
@albabosh How did you fix this?

**Comment by cenobitedk** [comment]
Solution:
https://stackoverflow.com/questions/4269922/permission-denied-publickey-when-deploying-heroku-code-fatal-the-remote-end

**Comment by albabosh** [comment]
https://devcenter.heroku.com/articles/keys
