### ISSUE TITLE
How to install plugins with composer ?

### ISSUE THREAD

**Issue by albabosh** [xyu/heroku-wp#140]
How to install plugins with composer ?

**Comment by ryanburnette** [comment]
https://wpackagist.org/

**Comment by wzul** [comment]
how if I want to install plugin from github which is not published on wpackagist.org and wordpress plugin repository?

**Comment by ryanburnette** [comment]
That’s already being done in the repo. You can infer the procedure by
looking at composer.json.

Also look at the composer docs.

**Comment by wesleyfsmith** [comment]
Could someone clarify to me where in the comoser.json file this is happening? I'd love to install some plugins that aren't available on wpackagist

**Comment by punggolzenith** [comment]
https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md
