### ISSUE TITLE
Composer wpackagist missing file error

### ISSUE THREAD

**Issue by bruced** [xyu/heroku-wp#149]
https://wpackagist.org/p/providers-2014%2476c91c489083ad647d75a2ac0de5  
  0e153a8c33c6b1be2dfb06f4a66944b249b4.json
File could not be downloaded (HT  
  TP/1.1 404 Not Found)

**Comment by ryanburnette** [comment]
Is this error persisting for you?

**Comment by xyu** [comment]
@bruced that sounds like a transient wpackagist error, I'm going to close this issue if it persists please open a new issue.
