### ISSUE TITLE
Admin Login fails with paid Memcachier plans

### ISSUE THREAD

**Issue by tiefenb** [xyu/heroku-wp#15]
I noticed a problem with the memcachier addon.
After I changes my MemCachier to any paid plan, I can't login into wp-admin (It redirects me back to the login panel without an error message).

After changing the plan to the free dev-version, it works again.

**Comment by basilmon92** [comment]
hi @tiefenb can you commit your working heroku-wp code ?

**Comment by xyu** [comment]
I have deprecated the HHVM version and created a new PHP 7 version of Heroku WP. As part of that I have created a new default branch as not to break backwards compat.

In the new branch I am now supporting the new Heroku Redis (https://elements.heroku.com/addons/heroku-redis) datastore as the in memory object-cache store. As such I'm closing this issue.
