### ISSUE TITLE
Authy has been deprecated

### ISSUE THREAD

**Issue by fagiani** [xyu/heroku-wp#150]
Hello @xyu , just a heads up as the Authy plugin has been deprecated.

Do you envision other plugin to replace that functionality within this project?

Here is the official post: https://authy.com/blog/deprecating-authy-wordpress/

Keep rocking!

**Comment by ryanburnette** [comment]
I propose that Authy never belonged to this project anyway. The goal should be for this project to contain the components necessary to run WordPress on Heroku.

Authy or something like it is certainly a good choice, but its place is not here.

Let's just remove it without a replacement.
