### ISSUE TITLE
Non-standard mysql port

### ISSUE THREAD

**Issue by ryanburnette** [xyu/heroku-wp#159]
Is it just me or does this not take into account non-standard port?

https://github.com/xyu/heroku-wp/blob/master/public/wp-config.php#L85

I believe this will break if you're using a port other than 3306.

@xyu What do you think?

I can PR if I'm reading this right.

**Comment by xyu** [comment]
That is correct this does not set the port if it's non-standard.

**Comment by ryanburnette** [comment]
I'll PR.

**Comment by xyu** [comment]
Thanks for fixing in #160 @ryanburnette!
