### ISSUE TITLE
Error running heroku run wp core install

### ISSUE THREAD

**Issue by janoist1** [xyu/heroku-wp#172]
> Running wp core install --url=myapp.herokuapp.com "--title=MyApp.io CMS" --admin_user=admin --admin_password=admin --admin_email=myapp@example.com on ⬢ myapp... up, run.8529 (Free)
2020-02-26 17:59:23.735 +0000 (44 44) warning: couldn't find daemon='/usr/bin/newrelic-daemon' (ENOENT)
2020-02-26 17:59:23.801 +0000 (4 4) warning: couldn't find daemon='/usr/bin/newrelic-daemon' (ENOENT)
WordPress database error Table 'fzxqri1bzevbfdf5.wp_options' doesn't exist for query INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('uninstall_plugins', 'a:2:{i:0;b:0;s:45:\"secure-db-connection/secure-db-connection.php\";s:32:\"WP_SecureDBConnection::uninstall\";}', 'yes') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`option_value`), `autoload` = VALUES(`autoload`) made by require_once('/app/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), include_once('/mu-plugins/secure-db-connection/secure-db-connection.php'), register_uninstall_hook, update_option, add_option
Error: 'core' is not a registered wp command. See 'wp help' for available commands.

**Comment by DSaxon** [comment]
change `wp-cli` to 'wp-cli-bundle' in composer.json
