### ISSUE TITLE
Not able to update composer.lock file

### ISSUE THREAD

**Issue by micahwalter** [xyu/heroku-wp#20]
I keep getting this error when trying to update via composer.

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package hhvm could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by griffiths** [comment]
I'm getting the following message when running composer update --ignore-platform-reqs:

 [RuntimeException]                                   
 The "--ignore-platform-reqs" option does not exist.

Anyone know how to resolve this? Thank you!

**Comment by xyu** [comment]
@griffiths try updating composer with `composer selfupdate` and try again.

**Comment by griffiths** [comment]
Nice one, thank you!
