### ISSUE TITLE
bundle wp-amazon-s3-and-cloudfront instead of wpro

### ISSUE THREAD

**Issue by tomcastleman** [xyu/heroku-wp#29]
Hi there,

I have found wpro to be buggy, poorly written & maintained. I gave up with it and discovered the following plugins which have worked very well with no hassle and provide a far better experience:

https://github.com/deliciousbrains/wp-amazon-web-services
https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront

I suggest you'd like to bundle these instead of wpro.

Thanks

Tom

**Comment by tiefenb** [comment]
I  switched from wpro to Windows Azure Storage: https://wordpress.org/plugins/windows-azure-storage/

**Comment by xyu** [comment]
@tomcastleman can you detail some of the issues you are seeing with WPRO so that I can better understand the problem?

**Comment by anthonysexton** [comment]
The WPRO plugin has been rewritten (Thanks @alfreddatakillen) so @tomcastleman you should expect an update soon

**Comment by atbyrd** [comment]
My files are not being uploaded to s3 when using WPRO.

**Comment by xyu** [comment]
I have deprecated the HHVM version and created a new PHP 7 version of Heroku WP. As part of that I have created a new default branch as not to break backwards compat.

In the new branch I am now bundling the much newer and better maintained S3 Uploads from Human Made / @joehoyle instead:
http://github.com/humanmade/S3-Uploads

As such I'm marking this issue as closed.
