### ISSUE TITLE
404's for Permalinks in local development

### ISSUE THREAD

**Issue by michaelward82** [xyu/heroku-wp#35]
I'm getting 404 errors for permalinks in local development.

You can see my full repo here: https://github.com/michaelward82/lisa/tree/production

Let me know which logs you might like to see to help diagnose the issue.

**Comment by BilboAtBagEnd** [comment]
I'm seeing this too. It stems somehow from the configuration in this file: 

  support/vagrant/root/etc/nginx/sites-available/herokuwp.conf

**Comment by dmtintner** [comment]
@xyu any thoughts on this? I'm getting this as well

**Comment by michaelward82** [comment]
Something must have changed regarding the dependency versions in this project. The vagrant instance worked flawlessly for me in the same host environment around 2 months ago.

**Comment by dmtintner** [comment]
same here. Anyone find a fix?

**Comment by michaelward82** [comment]
I've not had time to investigate yet, and I'm unfamiliar with nginx which is where I suspect the problem lies.

**Comment by dmtintner** [comment]
Nothing in the nginx error.log and in access.log I can just see the 404, no other info

192.168.50.1 - - [17/Apr/2015:11:16:50 +0000] "GET /best-design-resources HTTP/1.1" 404 49 "http://herokuwp.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"

**Comment by xyu** [comment]
I suspect that this is due to some change in HHVM, I'll investigate this weekend.

**Comment by dmtintner** [comment]
I see that HHVM was updated to version 3.6 in March, probably around the
time this started http://hhvm.com/blog/8849/hhvm-3-6-0

**Comment by xyu** [comment]
FWIW, Heroku is currently on HHVM 3.5.1 / Nginx 1.6.0 in case we find an incompatibility.

**Comment by dmtintner** [comment]
Do we need to roll back the version of hhvm and update the composer.json to
3.5 locally too then? If there's no fix for 3.6 yet

**Comment by xyu** [comment]
It appears this issue is currently being discussed here: https://github.com/facebook/hhvm/issues/4986

It's not clear if this is considered an HHVM bug or configuration issue.

**Comment by dmtintner** [comment]
I rolled back the version of HHVM to 3.5.1 and everything works again.

$ ssh vagrant 
then instructions for rolling back here: https://gist.github.com/dmtintner/566e93ccccfb871774d0

**Comment by dmtintner** [comment]
I changed the install.sh to do this automatically for now. 

You can see the code in this pull request https://github.com/xyu/heroku-wp/pull/40

**Comment by xyu** [comment]
#40 was merged closing this issue.
