### ISSUE TITLE
Gzip compression not actually turned on

### ISSUE THREAD

**Issue by BilboAtBagEnd** [xyu/heroku-wp#37]
I noticed that gzip compression was not turned on for ngnix. There is a missing statement, in particular: 

    gzip_proxied any;

This is because any Heroku instance is proxied, so ngnix will ignore gzip compression directives unless this statement is present. 

Thanks, 
Ava

**Comment by xyu** [comment]
Oops, I guess I never really saw this because I was running everything through CloudFlare. I assume nginx will still respect the `Accept-Encoding` header even with that parameter set to any? I'll test that out this weekend and make the change unless you've already tested it.
