### ISSUE TITLE
Request Dockerfile

### ISSUE THREAD

**Issue by philipz** [xyu/heroku-wp#4]
This project is awesome!!!  Would you translate to dockerfile format? Thank you!!!

**Comment by xyu** [comment]
Instead of Docker I've included a Vagrant config as running this locally involves running both MySQL and HHVM. Also it's easier to share files between the host and VM for local dev this way.

**Comment by sformisano** [comment]
Actually by using a volume you can also share files easily with Docker! And running a docker container is much lighter than a vm
