### ISSUE TITLE
How can we upgrade to Wordpress 4.2?

### ISSUE THREAD

**Issue by jordanegiuly** [xyu/heroku-wp#41]
Hello,

I'm using heroku-wp to deploy a wordpress with Heroku. A new version of Wordpress (4.2.1) was released a week ago. 
How can we upgrade Wordpress version ?

Thank you,
Jordane

**Comment by BilboAtBagEnd** [comment]
You can update composer.json and recreate composer.lock. Then deploy (try
this on a forked Heroku application first, of course, if your WordPress is
currently being used/viewed by other folks).

**Comment by jordanegiuly** [comment]
Hello,
Thank you for your quick response. I'll try that and let you know if it worked.
Best

**Comment by kim07** [comment]
helpful for me as well

**Comment by willhlaw** [comment]
Verified that it indeed works. 

Steps
- Update composer.json file with new version string
- Run following command and use --ignore-platform-reqs to bypass hhvm requirement (see [comment here](https://github.com/heroku/heroku-buildpack-php/blob/master/bin/compile#L157) in buildpack source)

- `$> composer update --ignore-platform-reqs`

Example run
>$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
>    - This package requires hhvm ~3.2 but you are running this with PHP and not HHVM.
>
>$ composer update --ignore-platform-reqs
>Loading composer repositories with package information
>Updating dependencies (including require-dev)
>  - Installing composer/installers (v1.0.21)
>    Downloading: 100%         
>
>  - Installing wordpress/wordpress (4.2.2)
>    Down    Downloading: 100%
> ...

**Comment by riyadhalnur** [comment]
the new update (55d0d35) now installs WP 4.3

**Comment by denisprado** [comment]
There is another way to update? I do not have permission to install composer..

**Comment by xyu** [comment]
Closing this WP core has been upgraded.
