### ISSUE TITLE
Give instructions on upgrading WordPress itself

### ISSUE THREAD

**Issue by jgarber** [xyu/heroku-wp#51]
Tried to upgrade to 4.3.1. `composer update --ignore-platform-reqs` wasn't sufficient. The README should provide better instructions or perhaps use https://github.com/johnpbloch/wordpress-core-installer to declare the dependency more simply?

**Comment by atbyrd** [comment]
@jgarber Did you update composer.json

```json
"repositories": [{
    "type": "package",
    "package": {
      "name": "WordPress/WordPress",
      "version": "4.4",
      "dist": {
        "type": "zip",
        "url": "https://github.com/WordPress/WordPress/archive/4.4.zip"
      }
    }
  }
```

**Comment by xyu** [comment]
This is the correct way to update WP core :)
