### ISSUE TITLE
CORS issue 

### ISSUE THREAD

**Issue by samuelmadeu** [xyu/heroku-wp#52]
"Font from origin 'http://example.herokuapp.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://blog.example.com' is therefore not allowed access." 

I have been receiving this error which has made some of my fonts inactive on my blog's domain. 

I understand that NGINX does not allow access to the .htaccess file, is there a similar fix that can be done in the app_nginx.conf file or is there something else I can do to fix this issue.

**Comment by declanelcocks** [comment]
@samuelmadeu Did you happen to fix this issue?

**Comment by xyu** [comment]
@samuelmadeu @declanelcocks you can add headers with the `add_header` directive to `/support/app_nginx.conf`

See:
http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header
