### ISSUE TITLE
Waiting for Heroku Redis to provision [ ]./init.sh: line 52

### ISSUE THREAD

**Issue by pdnellius** [xyu/heroku-wp#60]
Getting this error during setup:
```
Waiting for Heroku Redis to provision [ ]./init.sh: line 52: local: can only be used in a function
./init.sh: line 55: ((: ? != 0: syntax error: operand expected (error token is "? != 0")
./init.sh: line 62: print: command not found
 ▸    local database is not available, try again in a few minutes
 ▸    local database is not available, try again in a few minutes
```
I then get "Error establishing connection to database" when I visit the site.

Is this a bug? Or am I doing something wrong?

**Comment by aaronchi** [comment]
There seems to be a bunch of errors with the current init script. I tried to set this up yesterday and there are some obivous errors with commands that don't work cross system `print` vs `printf`, `local`, etc.

But there are also problems with the setup script itself. First of all, it creates a database with the ENV variable `WP_DB_URL` but the wp-config file is looking for `WP_DB`. Even when I made some of these changes manually, I couldn't get the site to connect to the database as wordpress claimed it was looking for a database at 127.0.0.1

Someone needs to review the init script and make sure that it's actually working.

**Comment by xyu** [comment]
@pdnellius thanks for pointing this out 6788ded6a2fb97e00e7d7a2e875b9ed4125f64e7 fixes the waiting for provision problem.

**Comment by xyu** [comment]
I've fixed the problems with the `init.sh` script and a couple documentation issues as well in the commits below:

https://github.com/xyu/heroku-wp/compare/f372a79...81625c6

Everything should be working now I'm going to mark this as resolved / closed. @pdnellius / @aaronchi  please let me know if either of you are still running into problems.
