### ISSUE TITLE
Vagrant: HHVM errors during provisioning

### ISSUE THREAD

**Issue by pdnellius** [xyu/heroku-wp#62]
Getting the following errors during VM provisioning. I'm also unable to reach the VM at heroku.local on my local machine, even after making the suggested host entry.

```
==> herokuwp: Unpacking hhvm (3.5.1~trusty) ...
==> herokuwp: dpkg: dependency problems prevent configuration of hhvm:
==> herokuwp:  hhvm depends on libboost-filesystem1.54.0; however:
==> herokuwp:   Package libboost-filesystem1.54.0 is not installed.
==> herokuwp:  hhvm depends on libboost-program-options1.54.0; however:
==> herokuwp:   Package libboost-program-options1.54.0 is not installed.
==> herokuwp:  hhvm depends on libboost-system1.54.0; however:
==> herokuwp:   Package libboost-system1.54.0 is not installed.
==> herokuwp:  hhvm depends on libboost-system1.54.0; however:
==> herokuwp:   Package libboost-system1.54.0 is not installed.
==> herokuwp:  hhvm depends on libboost-regex1.54.0; however:
==> herokuwp:   Package libboost-regex1.54.0 is not installed.
==> herokuwp:  hhvm depends on libc-client2007e; however:
==> herokuwp:   Package libc-client2007e is not installed.
==> herokuwp:  hhvm depends on libmcrypt4; however:
==> herokuwp:   Package libmcrypt4 is not installed.
==> herokuwp:  hhvm depends on libmemcached10; however:
==> herokuwp:   Package libmemcached10 is not installed.
==> herokuwp:  hhvm depends on libonig2; however:
==> herokuwp:   Package libonig2 is not installed.
==> herokuwp:  hhvm depends on libtbb2; however:
==> herokuwp:   Package libtbb2 is not installed.
==> herokuwp:  hhvm depends on libjemalloc1 (>= 3.0.0); however:
==> herokuwp:   Packa
==> herokuwp: dpkg: error processing package hhvm (--install):
==> herokuwp:  dependency problems - leaving unconfigured
==> herokuwp: Processing triggers for ureadahead (0.100.0-16) ...
==> herokuwp: Errors were encountered while processing:
==> herokuwp:  hhvm
```

Then...

```
==> herokuwp: Cannot create cache directory /root/.composer/cache/repo/https---wpackagist.org/, or directory is not writable. Proceeding without cache
==> herokuwp: Cannot create cache directory /root/.composer/cache/repo/https---wp-cli.org-package-index/, or directory is not writable. Proceeding without cache
==> herokuwp: Cannot create cache directory /root/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
==> herokuwp: Cannot create cache directory /root/.composer/cache/files/, or directory is not writable. Proceeding without cache
==> herokuwp: Loading composer repositories with package information
==> herokuwp: Installing dependencies (including require-dev) from lock file
==> herokuwp: Your requirements could not be resolved to an installable set of packages.
==> herokuwp:
==> herokuwp:   Problem 1
==> herokuwp:     - This package requires php ~7.0 but your HHVM version does not satisfy that requirement.
```

**Comment by xyu** [comment]
I have not gotten a chance to update the vagrant install for PHP7 yet after changing this repo over from using Nginx/HHVM.

**Comment by ArpiJakab** [comment]
Hi xyu, great work putting this project together. I'm seeing the same problem on "vagrant up". Do you have a workaround? Thanks!

**Comment by xyu** [comment]
Unfortunately not, I'm working off and on in getting a new vagrant config setup but been busy with other things. However because this is Heroku you can actually just spin up another app and push to that development / staging app instead of your production app.

It's not as great as vagrant because you need to wait for a slug to rebuild but it's a more accurate testing environment.

**Comment by ArpiJakab** [comment]
Great point, I'll give the Heroku pipeline workflow a go.

**Comment by lyxard** [comment]
Hi there!,
I'm a newbie to linux, vagrant.;however, it does seem that an easier way to setup the vm is to use vagrant with puphet. Let me know what you guys think! Thank you!

**Comment by tomas-st** [comment]
I fixed vagrant up problem for hhvm dependency for my setup by adding the --ignore-platform-reqs flag to install.sh. It should be used by composer update anyway.

Another bug after successful provisioning is that nginx config is not correctly referenced within herokuwp.conf. I will try to prepare a push request. Missing is https configuration for vagrant. Besides that vagrant wordpress is running fine atm.

**Comment by xyu** [comment]
I'm going to mark this thread as closed, with the changes that @quasivivo made in #80 based on comments from @tomas-st and a bunch of changes I made in https://github.com/xyu/heroku-wp/commit/af3cd22f3eb1059f0a7140551722f5d88843b1d6 the Vagrant local dev env should be working again. This time with Nginx and PHP7 which is what this repo is deploying to Heroku by default now.
