### ISSUE TITLE
Best Practice w/ Custom Theme + Plugins

### ISSUE THREAD

**Issue by gil--** [xyu/heroku-wp#66]
I'm a little confused on how we should go about using this with a private repo containing wp-content that houses our custom plugins and theme. Normally I can either deploy entire WP site Github repo to server or add the wp-content folder as a repo on the server and pull whenever I make plugin/theme/wp changes.

"Because a file cannot be written to Heroku's file system, updating and installing plugins or themes should be done locally and then pushed to Heroku."

What does that mean? SCP files to the heroku instance? Sorry I'm just new to Heroku/Composer for Wordpress.

**Comment by xyu** [comment]
You can add custom plugins and themes to the `public/wp-content` here:

https://github.com/xyu/heroku-wp/tree/nginx-php7/public/wp-content

Anything checked into this dir will be merged with the plugins or themes specified in the composer config when deployed to Heroku.

**Comment by gil--** [comment]
Thanks! Makes sense.

 I also went ahead and read up more on Heroku. For anyone else in the future that is/was confused checkout these guides:

[How Heroku Works](https://devcenter.heroku.com/articles/how-heroku-works)
[Deploying with Git](https://devcenter.heroku.com/articles/git)
[Github Integration](https://devcenter.heroku.com/articles/github-integration)

**Comment by evanjmg** [comment]
this doesn't seem to work I've created a folder /themes git committed it and also just tried inside wp-content. Did this break?
