### ISSUE TITLE
Leverage browser caching

### ISSUE THREAD

**Issue by punggolzenith** [xyu/heroku-wp#72]
Hi xyu, thanks for your wonderful repo. The technology driving it is really amazing. I managed to up a rather static website rapidly on punggolgp.com with a standard paid theme on Genesis framework. 

I wanted to check with you this thing about "browser cache". According to the other internet tutorials we can try to edit the htaccess, but I notice that in this installation the htaccess is not accessible. I then tried to install a few plugins, but it didn't work too. 

Sorry I'm not a coder, I don't really understand the full insides of this installation. Could you enlighten  me please?

**Comment by punggolzenith** [comment]
Oh found it. Should be in nginx.inc.conf. Will let u know if I manage to succeed

**Comment by xyu** [comment]
Just to note this repo includes https://github.com/Automattic/batcache already preconfigured so not only is your site already leveraging browser caching but it's also using a memcache like store (redis) to make everything even faster for first time visitors.

I'm going to close this issue for now but let me know if you run into more problems.
