### ISSUE TITLE
PHP 7.1 not compatible

### ISSUE THREAD

**Issue by punggolzenith** [xyu/heroku-wp#74]
In this current installation of wordpress, the PHP is set to be "~7", but PHP 7.1 appears to be not compatible with the current installation. There will be an error: 
"Warning: Parameter 1 to wp_default_styles() expected to be a reference ....."
Not a big issue, seems to be a wordpress problem.

Anyways, after setting the "php": "7.0.*", to rollback to PHP version it appears to fix the problem.

**Comment by dougq** [comment]
It appears that another way to make this warning go away (while sticking with PHP 7.1) is to upgrade your WordPress version from 4.6.1 to 4.7.
