### ISSUE TITLE
Adding new wordpress themes 

### ISSUE THREAD

**Issue by stanleycyang** [xyu/heroku-wp#82]
There is currently no button that allows for new wordpress themes to be used: 

![screen shot 2017-01-17 at 10 13 51 am](https://cloud.githubusercontent.com/assets/3037893/22033521/aa6fe304-dc9d-11e6-92d5-182c1333cbec.png)

I'm not sure if this is by design for security purposes or there is a way to do it that I'm not aware of. 

Any direction on this would be useful. 

Thanks!

**Comment by punggolzenith** [comment]
Heroku has an ephemeral file system. Anything u install with the app will be deleted when the app restarts. (And it will happen everyday randomly according to heroku)

U can try to install via composer.json 

Or the easier way is to copy the themes folder manually into
Public-->wp-content-->themes

**Comment by stanleycyang** [comment]
Thanks! This worked out well
