### ISSUE TITLE
Enhancement: WP multisites

### ISSUE THREAD

**Issue by punggolzenith** [xyu/heroku-wp#97]
Hi dear all, i'm trying to squeeze every single bit of juice out from a single heroku dyno.

I tried to install WP multisites under Nginx subdomains.

However, i failed terribly, i cannot seem to write in the correct configurations in the nginx.inc.conf  file. 

Has anyone tried to do the same and succeeded? Or any pointers.

I tried using [this](https://easyengine.io/wordpress-nginx/tutorials/multisite/subdomains/minimal/).

**Comment by xyu** [comment]
The dyno will listen to any hostname so you should be able to just add domains to your Heroku app then configure the mappings of domains to sites in WP. Having said that I have never run a multisite install so I'm not quite sure if there's anything else that's needed.

**Comment by dgursh** [comment]
+1 I think possible multisite install would be an excellent feature for heroku-wp

**Comment by punggolzenith** [comment]
i've tried a few other ways to deploy wp since i started this thread, but none seems as easy or as fun as this repo. So far nothing is as fast to provision and edit (at least not aws, not kubernetes or docker). (I am not a coder, just a hobbyist).

Anyway, i did manage to make some headway into this project.

1) Add the following lines in wp-config.php

`/* Multisite */
define( 'WP_ALLOW_MULTISITE', true );
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
define('DOMAIN_CURRENT_SITE', 'wpmuats.herokuapp.com');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
`

2) Log into your wordpress installation and select **SUBDIRECTORY** INSTALL

3) Add the following lines to nginx.rewrites.conf 

` if (!-e $request_filename) {
    rewrite /wp-admin$ $scheme://$host$uri/ permanent; 
    rewrite ^(/[^/]+)?(/wp-.*) $2 last; 
    rewrite ^(/[^/]+)?(/.*\.php) $2 last;
  }
  set $cache_uri $request_uri;

    # Don't cache uris containing the following segments
  if ($request_uri ~* "(/wp-admin/|/xmlrpc.php|/wp-(app|cron|login|register|mail).php|wp-.*.php|/feed/|index.php|wp-comments-popup.php|wp-links-opml.php|wp-locations.php|sitemap(_index)?.xml|[a-z0-9_-]+-sitemap([0-9]+)?.xml)") {
    set $cache_uri 'NULL';
  }

    # Don't use the cache for logged in users or recent commenters
  if ($http_cookie ~* "comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_logged_in") {
    set $cache_uri 'NULL';
  }`

4) Yay! You can add a few more sites, i think... So far i've only done it with a fresh install, haven't added any users or functions or themes onto it yet.

5) Next i will try domain mapping probably using this in nginx.inc.conf

`server {
  ##DM - uncomment following line for domain mapping 
  #listen 80 default_server;
  server_name yourdomain.com;
  ##DM - uncomment following line for domain mapping
  #server_name_in_redirect off; `

I will let u know if i am able to succeed.

References: 
[Wordpress multisite](https://codex.wordpress.org/Create_A_Network)
[
Nginx redirect loop](https://matiasvad.com/fixing-nginx-redirect-loop-wordpress-multisite/)

**Comment by punggolzenith** [comment]
yes, it succeeded! After that just point your whatevercustomdomain.com--> blahblah.herokudns.com and www.whatevercustomdomain.com-->www.blahblah.herokudns.com, then change the WP address of the particular site in the wordpress installation, and thats all!, so easy.

A few catch:
1) Separate cookie generated for each site. ie. login multiple times, small problem.
2) Can experience slowing, especially when a lot of things are happening at the same time, i mean, how much can you push 1 heroku dyno? So try to offload everything, S3, SMTP, cron whatever.
3) Watch the database size, once it reaches 5MB, there will be no warning, just crash and there goes your database. Thanks autobus.io for keeping a copy of my db...

**Comment by romantico** [comment]
Really having trouble Implementing this one.
Need help
