### ISSUE TITLE
ionCube Loader

### ISSUE THREAD

**Issue by toddheslin** [xyu/heroku-wp#98]
I have a plugin which requires ionCube Loader. I'm not familiar with how the Heroku architecture would support this and where in this project it should be added. Part of build process?

Not sure, so leaving this out there to be shut down or considered as an addon.

**Comment by xyu** [comment]
Hmm... I'm not really sure how ionCube works / have never used it however it seems like it can be used even on shared hosts so seems like it would be possible to use with this repo. Any php.ini customizations that are needed can be made in this file:

https://github.com/xyu/heroku-wp/blob/nginx-php7/support/php.ini

I'm pretty sure no FPM configs are needed but if they are they can be customized here:

https://github.com/xyu/heroku-wp/blob/nginx-php7/support/php-fpm.inc.conf

**Comment by toddheslin** [comment]
Thanks @xyu I figured this out and it wasn't too complicated. I'll close this issue but for anyone searching in the future here are the steps:

1. Download the ionCube Loader `ioncube_loaders_lin_x86-64.tar.gz` from [their website here](http://www.ioncube.com/loaders.php)
2. Extract and grab the `ioncube_loader_lin_7.0.so` and add to your git `wp-content/plugins/iconcube/` folder
3. In `support/php.ini` add the following lines

```
; ioncube loader
zend_extension = /app/public.built/wp-content/plugins/ioncube/ioncube_loader_lin_7.0.so
```

Given these steps, you should be able to unpack any encrypted plugins that use the ionCube Loader
