### ISSUE TITLE
Doc Needed: How to install plugins

### ISSUE THREAD

**Issue by chrisbutler** [xyu/heroku-wp#99]
i've tried all sorts of composer options, and put the plugin folder in every location possible

what the heck am i doing wrong?

**Comment by chrisbutler** [comment]
ended up using https://github.com/ellefsen/wordpress-heroku-php but i'm still curious...

**Comment by xyu** [comment]
To install plugins you will need to add them to the require section of composer:

https://github.com/xyu/heroku-wp/blob/cfe710/composer.json#L24-L27

And then run composer update in order to update the composer lock file

```
$ bin/composer update --ignore-platform-reqs
```

Commit both `composer.json` and `composer.lock` then push to deploy.

I'm going to change the title of this issue to improve the documentation.

**Comment by punggolzenith** [comment]
dude u got to chill the f*ck out man.. hahaha
got to start to understand the technology u are working with...

two ways
1) google
2) google again, but no

actually the best is like what xyu said.

1) use composer (google about how to use it) , but u can start by going to [https://wpackagist.org/](https://wpackagist.org/ )  then try to see what is the "name" of the plugin you need, then key in the version number.  

on the composer.json   , try going below the line on "wpackagist-plugin/secure-db-connection.....
then try typing in all the whatever plugins u need.  of course if you want to use plugins from other sources you could, but u need to define the repo below if im not wrong...

Then install composer if u havent done so, then need to run the  $ bin/composer update --ignore-platform-reqs, then just push the changes.

2) manual installation
try putting it in public>wp-content>plugins>(folder containing your plugins).

If you still cant understand, then perhaps wix might be a better option for u  :/

**Comment by chrisbutler** [comment]
@xyu thanks for getting back to me. i tried to use a local plugin following this:

```To customize the site simply place files into /public which upon deploy to Heroku will be copied on top of the standard WordPress install and plugins specified by Composer.```

Between that and https://github.com/xyu/heroku-wp/issues/66#issuecomment-253098019 I was under the impression that I needed to place the plugin files in either ```public/``` or ```public/wp-content/```, and placing the folder there simply did not work

it's pretty obvious to me in retrospect that i needed to create the ```plugins``` folder myself inside of ```wp-content/``` (and that the same is the case for themes)
